#!/bin/bash

pandoc --css=http://getbootstrap.com/dist/css/bootstrap.css \
       --include-before=before.html \
       --include-after=after.html \
       --table-of-contents \
       -t html5 \
       -o CartaOrganica.html \
       CartaOrganica.markdown
