#!/bin/bash
FORMATS=(html5 pdf epub mediawiki)

for format in ${FORMATS[@]}; do
# Si no está en before lo agregamos
  grep -q $format before.html || \
  echo "<a href=\"CartaOrganica.${format}\">${format}</a>" \
  >> before.html

  pandoc --css=http://getbootstrap.com/dist/css/bootstrap.css \
        --include-before=before.html \
        --include-after=after.html \
        --latex-engine=xelatex \
        --table-of-contents \
        -t ${format} \
        -o CartaOrganica.${format} \
        CartaOrganica.markdown
done

mv CartaOrganica.html{5,}
